### ISSUE TITLE
Request to Reinstate Semantic Versioning for Clarity and Compatibility

### ISSUE THREAD

**Issue by relatedcode** [swiftlang/swift-markdown#178]
Semantic Versioning, often abbreviated as SemVer, is a versioning scheme for software aimed at conveying meaning about the underlying changes with each release. It's structured as `MAJOR.MINOR.PATCH`, where:

- **MAJOR** version increases indicate incompatible API changes,
- **MINOR** version increases add functionality in a backwards-compatible manner,
- **PATCH** version increases are for backwards-compatible bug fixes.

This system helps developers and users understand the impact of updating to a new version without having to delve deep into the release notes. For instance, increasing the MAJOR version signals that users might need to make significant changes on their end, while a PATCH update suggests minor, typically safe improvements.

https://semver.org

**Comment by fumito-ito** [comment]
+1 

In addition, I request to reinstate semantic version to facilitate referencing from other libraries.

I am referencing this library from a package I am creating, but I cannot use `package(url:from:)` in Package.swift and am forced to use `package(url:revision:)`.

**Comment by twostraws** [comment]
I think(?) this same problem is hitting my Ignite project: SPM is complaining that adding Ignite fails because it relies on an unstable package: swift-markdown. I might switch to the solution suggested by @fumito-ito, but actual semver would be most welcome.

**Comment by fumito-ito** [comment]
Follow-up:

@twostraws 

Unfortunately the https://github.com/apple/swift-markdown/issues/178#issuecomment-2116554031 solution did not work.

This is because `package(url:revision:)` cannot be used as a stable version specification, as described in the SPM documentation.

https://github.com/apple/swift-package-manager/blob/4dc41b046381ddb9297127ccc83149994770b28c/Documentation/PackageDescription.md?plain=1#L400-L403

```
Note that packages which use commit-based dependency requirements can't be added as dependencies to packages that use version-based dependency requirements; you should remove commit-based dependency requirements before publishing a version of your package.
```

Since I had no choice, I forked `apple/swift-markdown` to set the release tag. This is not a good solution, but I think it is a practical one that can be taken under the current situation.

https://github.com/fumito-ito/swift-markdown/releases/tag/510.0.0

**Comment by Kyle-Ye** [comment]
https://forums.swift.org/t/swift-markdown-fatal-error-a-closed-block-directive-container-cannot-accept-further-lines-of-content/68127/5

Maybe we can expect a 0.4.0 release for release/5.10. cc @QuietMisdreavus

**Comment by fumito-ito** [comment]
🎉 https://github.com/apple/swift-markdown/releases/tag/0.4.0

**Comment by QuietMisdreavus** [comment]
Ah, yes, i didn't update this thread. I brought this up with the Swift Documentation Workgroup, and we decided to continue tagging releases based on Swift releases, backporting important bug fixes as necessary. I started off by tagging the `0.4.0` release from the `release/5.10` branch, as @fumito-ito spotted. In the future, as major Swift releases (stated subjectively, not referencing the semver number) finish, we will tag more Swift-Markdown releases. For example, when Swift 6.0 reaches its final release, i'll tag `0.5.0` based on the `release/6.0` branch. Thanks for your patience, everyone!

**Comment by QuietMisdreavus** [comment]
For the sake of this thread (since Swift-Markdown's versioning strategy is on people's minds again), i'll sum up the development and versioning strategy we've decided on:

- Because Swift-Markdown is primarily developed as a component of Swift-DocC, its development cycle lines up with the Swift toolchain's development cycle.
- This is reflected in its active branches: `main` is for in-development work, and releases of Swift will generate a `release/X.Y` branch corresponding to that release cycle. While a release is converging and focusing on bug fixes, work is landed in `main` then cherry-picked to the active `release/X.Y` branch as required.
- When a major release of Swift (stated subjectively, not in reference to semantic versioning) is published, we will create a new tag on [swift-cmark](https://github.com/swiftlang/swift-cmark) and Swift-Markdown. The latter will also create a `swift-markdown-0.X` branch to store the necessary commit that updates its Package.swift file to use the tag in swift-cmark.
- Critical bug fixes that land after a version is published can be cherry-picked onto the `swift-markdown-0.X` branch as necessary for a patch release to be tagged.
- New `release/X.Y` branches are regularly created from `main`, so work that lands in `main` will land in a tagged release once that corresponding Swift release is published, usually within a year.
- The decision criteria to publish a `1.0.0` release is Swift-Markdown is currently undefined.

For example, since Swift 6.0 was published today, i created `0.5.0` tags in both [swift-cmark](https://github.com/swiftlang/swift-cmark/releases/tag/0.5.0) and [Swift-Markdown](https://github.com/swiftlang/swift-markdown/releases/tag/0.5.0) based on their respective `release/6.0` branches. Work that is currently on `main` will only land in a tagged release once a new `release/X.Y` branch is created from `main` and a new Swift release is published based on that work.

**Comment by shagedorn** [comment]
Based on the above, I would assume a `0.6.0` tag for the latest Swift 6.1 release. However, the [release](https://github.com/swiftlang/swift-markdown/releases/tag/swift-6.1-RELEASE) currently has a different tag – can you please follow up and create a release with a semantic version? 🙏🏻

**Comment by mynona** [comment]
This approach is a huge pain!

**Comment by QuietMisdreavus** [comment]
> Based on the above, I would assume a `0.6.0` tag for the latest Swift 6.1 release. However, the [release](https://github.com/swiftlang/swift-markdown/releases/tag/swift-6.1-RELEASE) currently has a different tag – can you please follow up and create a release with a semantic version? 🙏🏻

Thanks for the reminder 😅 I've just tagged [`0.6.0`](https://github.com/swiftlang/swift-markdown/releases/tag/0.6.0) which should be usable as a package version. The other GitHub release was created in error and the latest should point to the `0.6.0` tag now.

**Comment by shagedorn** [comment]
This works, thank you!
