### ISSUE TITLE
How to parse mathematical formulas in swift-markdown

### ISSUE THREAD

**Issue by TabFunk** [swiftlang/swift-markdown#185]
How to parse textual math formula in swift-markdown to display as shown in the picture
![image](https://github.com/apple/swift-markdown/assets/156559896/a4e2561b-f70b-4bd9-a549-7dcb47bcc886)
![image](https://github.com/apple/swift-markdown/assets/156559896/919109a5-0ad2-44f3-bb52-60e9c6f24fc2)

**Comment by FirstStepzz** [comment]
same questions

**Comment by d-ronnqvist** [comment]
There is no markdown syntax for mathematical expressions. 

Depending on how you're using Swift-Markdown and what you're using to render the content, you may be able to use [MathML](https://en.wikipedia.org/wiki/MathML) to write the mathematical expressions. I believe that Swift-Markdown would skip over the MathML markup since it looks like HTML tags.

**Comment by d-ronnqvist** [comment]
This is better discussed in the Swift forums where mathematical typesetting has already been [brought up](https://forums.swift.org/t/docc-for-math/65508) [twice](https://forums.swift.org/t/pitch-mathematical-typesetting-in-docc/66418).

Note the consensus is that we shouldn't invent any new syntax to typeset mathematical expressions.
